name: Merge checks

on: push

jobs:
  tsc-and-test:
    runs-on: ubuntu-latest
    container: node:16.14

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: 1aO0ehpumCYQTVWRlE
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn install

      - name: Run test web
        run: yarn rw test web --no-watch --logHeapUsage
        env:
         TEST_DATABASE_URL: postgres://postgres:1aO0ehpumCYQTVWRlE@postgres:5432/postgres

      - name: Run build
        run: yarn rw build
